#simple base image using apt-cacher-ng, requires an running cache on build host
FROM debian:testing
#:stable


#does not work
RUN echo 'Acquire::http { Proxy "http://172.17.0.1:3142"; }; \ Acquire::https { Proxy "https://"; };' > /etc/apt/apt.conf.d/01proxy
RUN apt-get update && apt-get -y dist-upgrade && apt-get -y autoremove && apt-get autoclean
CMD /bin/bash
